# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the ast-v5_1_0-release-v5 branch
  push:
    branches: [ ast-v3_2_3-release-v5 ]
  pull_request:
    branches: [ ast-v3_2_3-release-v5 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: gcc:7
    strategy:
      matrix:
        target: ["nds64le-elf-newlib-v5d", "nds64le-linux-glibc-v5d"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y texinfo flex bison
          ./build_${{ matrix.target }}.sh

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.target }}

